from . import chatbot_session
from . import chatbot_message
from . import chatbot_contract
from . import product_soap
from . import product_deposit
from . import res_config_settings
from . import sign_request
from . import sign_template
from . import chat_umayor_config
